### ISSUE TITLE
no functions exported!?

### ISSUE THREAD

**Issue by dimpase** [dimpase/primecountpy#1]
It appears that only `__...` things are visible and callable in 
```
>>> import primecount as p
>>> p.<tab>
```
does not show the interesting things, but  only `__...` stuff.
And, `p.phi`, etc. are not known.

So this is probably a violation of some unwritten rules of cython that I just can't get.

@kliem, @mkoeppe

**Comment by kliem** [comment]
I can't reproduce this problem. However, I need to set `LD_LIBRARY_PATH="/usr/local/lib" to even import it. Once I have it imported everything works as expected.

**Comment by dimpase** [comment]
Thanks, it was very helpful.  After some thought, I see - what was happening for me, that it doesn't work if I invoke python3 in the directory of the package! Otherwise it works, duh...

**Comment by kliem** [comment]
I see. I thought this might have been the problem. But in my case I always got an immediate failure that `primecount.primecount` could not be found.

**Comment by dimpase** [comment]
Setting `LD_LIBRARY_PATH` should not be needed, I guess - should such things be handled by runpath stuff (I don't know much about it though). In Sage we don't set `LD_LIBRARY_PATH`, one way or another.

**Comment by kliem** [comment]
You should fix `AUTHORS`, remove `libc`, `libcpp` from `pyproject.toml` and fix the `url` in `setup.py`.

**Comment by kliem** [comment]
> You should fix `AUTHORS`, remove `libc`, `libcpp` from `pyproject.toml` and fix the `url` in `setup.py`.

See #2.

**Comment by dimpase** [comment]
sure, I know, it was just a draft. 
I posted it on GH, resisting the temptation to throw my laptop out of the window :-)

**Comment by dimpase** [comment]
by the way, see https://github.com/sagemath/memory_allocator/pull/5 - the URL there isn't quite right either

**Comment by dimpase** [comment]
>  I need to set `LD_LIBRARY_PATH="/usr/local/lib" to even import it. Once I have it imported everything works as expected.
> 
this is a cmake weirdness, which can be overcome by calling it with right options.
See https://github.com/kimwalisch/primecount/issues/45#issuecomment-973157503

**Comment by dimpase** [comment]
> I need to set `LD_LIBRARY_PATH="/usr/local/lib" to even import it.

Assuming your `ldconfig` caches `/usr/local/lib*`, just run `sudo ldconfig`.

**Comment by dimpase** [comment]
renamed the repo to `primecountpy`, to avoid pypi conflict, and allow forking `primecount` library. Update your git remotes
