### ISSUE TITLE
macOS linking problem

### ISSUE THREAD

**Issue by dimpase** [dimpase/primecountpy#3]
I can install primecount from source on macOS with homebrew just fine, and then build
this package, but apparently something needs to be done for linking/ld:
```
% python3
Python 3.9.7 (v3.9.7:1016ef3790, Aug 30 2021, 16:39:15) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import primecount
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dima/Library/Python/3.9/lib/python/site-packages/primecount-0.1.2-py3.9-macosx-10.9-x86_64.egg/primecount/__init__.py", line 1, in <module>
    from .primecount import *
ImportError: dlopen(/Users/dima/Library/Python/3.9/lib/python/site-packages/primecount-0.1.2-py3.9-macosx-10.9-x86_64.egg/primecount/primecount.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libprimecount.7.dylib
  Referenced from: /Users/dima/Library/Python/3.9/lib/python/site-packages/primecount-0.1.2-py3.9-macosx-10.9-x86_64.egg/primecount/primecount.cpython-39-darwin.so
  Reason: tried: '/usr/lib/libprimecount.7.dylib' (no such file)
```
How does one tell distutils/setuputils to use the correct location of the dylib, which is `/usr/local/lib/`? 

The `python3` in question is the binary install from cpython.org.

**Comment by dimpase** [comment]
@mkoeppe - any ideas?

**Comment by mkoeppe** [comment]
Did you install it from within a Sage build shell?

**Comment by dimpase** [comment]
no, outside of Sage.

**Comment by mkoeppe** [comment]
Don't try to figure out linker flags in the Python packaging. 
Just assume that they have been set up correctly. Which is true in our build env.

**Comment by dimpase** [comment]
it could be that libprimecount.dylib install should be tweaked for this, rather than Python. At least that was my experience on Linux, where the default process was missing final ldconfig call. 

It seems that cmake has  rather crazy defaults settings. On Linux it stips rpaths by default, on macOS it puts in these weird `@rpath` things in.

**Comment by dimpase** [comment]
it works if I start Python as follows:
```
% DYLD_LIBRARY_PATH=/usr/local/lib python3
```

So it's indeed just the question of environment. Is it possible to somehow bake the `DYLD_LIBRARY_PATH`, or something  equivalent, into the extension?

**Comment by dimpase** [comment]
I think I figured it out anyway, see README.

By the way, do you know about `pytest-cython`? Makes it test Cython files almost as trivial as Python ones, again , see README.
