### ISSUE TITLE
Bad example in README.md

### ISSUE THREAD

**Issue by thierry-FreeBSD** [dimpase/primecountpy#6]
The following example:
```
>>> import primecountpy as primecount
>>> primecount.pi(1000)
```
produces an error:
`AttributeError: module 'primecountpy' has no attribute 'pi'`

The correct syntax is:
```
from primecountpy.primecount import prime_pi
prime_pi(1000)
```

**Comment by dimpase** [comment]
Thanks for pointing this out :-)
