### ISSUE TITLE
GPL 2 or GPL 3?

### ISSUE THREAD

**Issue by saraedum** [dimpase/primecountpy#7]
The LICENSE file says GPL 3. However, the only license header I could find is in primecount.pyx and it says GPL 2.0 or later.

The license file is what matters I guess but maybe the header should be updated?

**Comment by dimpase** [comment]
I don't see why I made it GPL 3. Indeed, it can be made GPL 2+ instead.
The C++ library it interfaces is under a BSD (GPL-compatible) kind of license.

**Comment by saraedum** [comment]
@dimpase would you mind replacing the license file? Or should I create a PR?

**Comment by dimpase** [comment]
Hi,
PR will be easier.
Thanks
